#' Measure Word Frequency in Text
#'
#' @param text A text
#' @return A data frame
#' @examples
text <- "Coronaviruses are a group of viruses that cause diseases in mammals and birds. In humans, coronaviruses cause respiratory tract infections that are typically mild, such as some cases of the common cold (among other possible causes, predominantly rhinoviruses), though rarer forms such as SARS, MERS, and SARS-CoV-2 can be lethal. Human to human transmission of coronaviruses is primarily thought to occur among close contacts via respiratory droplets generated by sneezing and coughing. There are yet to be vaccines or antiviral drugs to prevent or treat human coronavirus infections."
wordFrequency.df <- MeasureWordFrequencyInText(text)


MeasureWordFrequencyInText <- function(text){
  words <- ExtractWordsOfText(text)
  wordFrequency.df <- as.data.frame(table(words))
  return(wordFrequency.df)
}
